# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d569c4ad26084fa5fb782781c144ae9369236695cf0009ba916bbfeff49698391e9f40373ffc2eb7e61de8760074dbbf57e4753bfcf5c5649813053d32e3de2

test:
  secret_key_base: f1d3132278397b6de7900576a35b58099855901b8f8831190395d0c2d362e9d38223ee9f7333db53275313a3aa5632c8820238592284cec65e1715584d914240

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
